# Generated by Django 4.1.3 on 2022-12-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEntrega', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='airbag',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='sigueJugando',
            field=models.BooleanField(blank=True),
        ),
    ]
