# Generated by Django 4.1.3 on 2022-12-19 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEntrega', '0002_alter_auto_airbag_alter_equipo_siguejugando'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='airbag',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='sigueJugando',
            field=models.BooleanField(),
        ),
    ]
